version:     "0001--9-Okt-2022"
copyright:   "2022"
author:      "Bintang Hari Pratama"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/bintangbhp/os222"
myloglink:   "os222/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
